import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { Check, Clipboard, Link2, Loader2, Plus, ShieldCheck, Users } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function BoardOnboarding({ preview = false }: { preview?: boolean }) {
  const { user, loading } = useAuth();
  const utils = trpc.useUtils();
  const previewMode = preview ? new URLSearchParams(window.location.search).get("onboardingMode") : null;
  const [mode, setMode] = useState<"choice" | "create" | "join">(previewMode === "create" ? "create" : previewMode === "join" ? "join" : "choice");
  const [boardName, setBoardName] = useState("");
  const [joinCode, setJoinCode] = useState("");
  const [created, setCreated] = useState<{ name: string; joinCode: string; inviteToken: string } | null>(null);
  const create = trpc.boards.create.useMutation({ onSuccess: (board) => { setCreated(board); utils.boards.mine.invalidate(); toast.success("تم إنشاء اللوحة بنجاح"); }, onError: (error) => toast.error(error.message) });
  const join = trpc.boards.joinByCode.useMutation({ onSuccess: () => { utils.boards.mine.invalidate(); toast.success("تم الانضمام إلى اللوحة"); }, onError: (error) => toast.error(error.message) });

  const copy = async (value: string, label: string) => { await navigator.clipboard.writeText(value); toast.success(`تم نسخ ${label}`); };
  const previewBoard = previewMode === "shared" ? { name: "إدارة العمليات", joinCode: "8H4K2PZQ", inviteToken: "preview-board-share-token-00000000" } : null;
  const sharedBoard = created ?? previewBoard;
  const inviteLink = sharedBoard ? `${window.location.origin}/join/${sharedBoard.inviteToken}` : "";

  if (loading && !preview) return <div dir="rtl" className="flex min-h-screen items-center justify-center bg-[#F7F9FC]"><Loader2 className="size-6 animate-spin text-[#6C8FB8]" /></div>;
  if (!user && !preview) return <div dir="rtl" className="fixed inset-0 flex min-h-screen items-center justify-center overflow-x-hidden overflow-y-auto bg-[#F7F9FC] p-6"><section className="w-full max-w-md rounded-2xl border border-slate-200 bg-white p-7 text-center shadow-sm"><span className="mx-auto flex size-12 items-center justify-center rounded-2xl bg-[#EDF4FA] text-[#52769F]"><ShieldCheck className="size-6" /></span><h1 className="mt-5 text-xl font-bold">ابدأ إدارة أعمال فريقك</h1><p className="mt-2 text-sm leading-6 text-[#7C8A9A]">سجّل الدخول أولًا لإنشاء لوحة أو الانضمام إلى لوحة موجودة.</p><Button onClick={() => startLogin()} className="mt-6 h-10 w-full bg-[#52769F] hover:bg-[#46698F]">تسجيل الدخول</Button></section></div>;
  if (sharedBoard) return <div dir="rtl" className="fixed inset-0 flex min-h-screen items-center justify-center overflow-x-hidden overflow-y-auto bg-[#F7F9FC] p-5"><section className="w-full max-w-xl rounded-2xl border border-slate-200 bg-white p-6 shadow-sm md:p-8"><span className="flex size-11 items-center justify-center rounded-2xl bg-emerald-50 text-emerald-700"><Check className="size-6" /></span><p className="mt-5 text-xs font-semibold text-[#6C8FB8]">لوحة جديدة</p><h1 className="mt-2 text-2xl font-bold">تم إنشاء «{sharedBoard.name}»</h1><p className="mt-2 text-sm leading-6 text-[#7C8A9A]">شارك أحد الخيارين التاليين مع أعضاء فريقك؛ سيحتاجون إلى تسجيل الدخول ثم ستضاف عضويتهم تلقائيًا.</p><div className="mt-6 space-y-4"><CopyField label="رمز الانضمام" value={sharedBoard.joinCode} onCopy={() => copy(sharedBoard.joinCode, "رمز الانضمام")} /><CopyField label="رابط مشاركة اللوحة" value={inviteLink} onCopy={() => copy(inviteLink, "رابط المشاركة")} /></div><Button onClick={() => window.location.assign("/")} className="mt-6 h-10 w-full bg-[#52769F] hover:bg-[#46698F]">الانتقال إلى لوحة العمل</Button></section></div>;
  const displayName = user?.name ?? "سارة الحربي";
  return <div dir="rtl" className="fixed inset-0 min-h-screen overflow-x-hidden overflow-y-auto bg-[#F7F9FC] px-5 py-10 md:flex md:items-center md:justify-center"><section className="mx-auto w-full max-w-4xl"><div className="mb-8 text-center"><span className="mx-auto flex size-11 items-center justify-center rounded-2xl bg-[#EDF4FA] text-[#52769F]"><Users className="size-5" /></span><p className="mt-4 text-xs font-semibold text-[#6C8FB8]">مرحبًا {displayName}</p><h1 className="mt-2 text-2xl font-bold tracking-tight md:text-3xl">كيف تود أن تبدأ؟</h1><p className="mt-2 text-sm text-[#7C8A9A]">أنشئ مساحة عمل لفريقك أو انضم لمساحة قائمة.</p></div>{mode === "choice" ? <div className="grid gap-4 md:grid-cols-2"><ChoiceCard icon={<Plus className="size-5" />} title="إنشاء لوحة إدارة جديدة" description="أنشئ لوحة لفريقك واحصل على رمز ورابط مشاركة للأعضاء." action="إنشاء لوحة" onClick={() => setMode("create")} /><ChoiceCard icon={<Link2 className="size-5" />} title="الانضمام للوحة إدارة موجودة" description="أدخل رمز اللوحة الذي أرسله لك المدير أو استخدم رابط المشاركة." action="انضمام للوحة" onClick={() => setMode("join")} /></div> : <div className="mx-auto max-w-md rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><button onClick={() => setMode("choice")} className="text-sm text-[#52769F]">← رجوع</button>{mode === "create" ? <><h2 className="mt-5 text-lg font-bold">إنشاء لوحة إدارة</h2><p className="mt-1 text-sm text-[#7C8A9A]">اختر اسمًا واضحًا للفريق أو القسم.</p><label className="mt-6 block text-sm font-medium text-[#52657A]">اسم اللوحة<Input autoFocus value={boardName} onChange={(event) => setBoardName(event.target.value)} placeholder="مثال: إدارة العمليات" className="mt-2 h-11 border-slate-200" /></label><Button disabled={create.isPending || boardName.trim().length < 2} onClick={() => create.mutate({ name: boardName.trim() })} className="mt-5 h-10 w-full bg-[#52769F] hover:bg-[#46698F]">{create.isPending ? "جارٍ الإنشاء..." : "إنشاء اللوحة"}</Button></> : <><h2 className="mt-5 text-lg font-bold">الانضمام إلى لوحة</h2><p className="mt-1 text-sm text-[#7C8A9A]">أدخل رمز اللوحة الذي شاركه مدير الفريق معك.</p><label className="mt-6 block text-sm font-medium text-[#52657A]">رمز اللوحة<Input autoFocus value={joinCode} onChange={(event) => setJoinCode(event.target.value.toUpperCase())} placeholder="مثال: 8H4K2PZQ" className="mt-2 h-11 border-slate-200 font-mono tracking-[.15em]" /></label><Button disabled={join.isPending || joinCode.trim().length < 6} onClick={() => join.mutate({ joinCode: joinCode.trim() })} className="mt-5 h-10 w-full bg-[#52769F] hover:bg-[#46698F]">{join.isPending ? "جارٍ الانضمام..." : "انضمام للوحة"}</Button></>}</div>}</section></div>;
}

function ChoiceCard({ icon, title, description, action, onClick }: { icon: React.ReactNode; title: string; description: string; action: string; onClick: () => void }) { return <button onClick={onClick} className="group rounded-2xl border border-slate-200 bg-white p-6 text-right shadow-sm transition hover:-translate-y-0.5 hover:border-[#BFD3E7] hover:shadow-md"><span className="flex size-10 items-center justify-center rounded-xl bg-[#EDF4FA] text-[#52769F]">{icon}</span><h2 className="mt-6 text-lg font-bold">{title}</h2><p className="mt-2 min-h-12 text-sm leading-6 text-[#7C8A9A]">{description}</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-[#52769F]">{action} <span>←</span></span></button>; }
function CopyField({ label, value, onCopy }: { label: string; value: string; onCopy: () => void }) { return <div><p className="mb-2 text-sm font-medium text-[#52657A]">{label}</p><div className="flex gap-2"><Input readOnly value={value} className="h-10 min-w-0 border-slate-200 bg-[#FCFDFE] text-xs" /><Button onClick={onCopy} variant="outline" className="h-10 shrink-0 border-slate-200 px-3 text-[#52769F]"><Clipboard className="size-4" /></Button></div></div>; }
